services:
  - type: web
    name: pledgewise-api
    env: node
    repo: https://github.com/webcave/plegdeCard2.git
    buildCommand: "ls -la && pwd && echo '--- Directory structure ---' && find . -type d -maxdepth 2"
    startCommand: "echo 'Starting app'"
    envVars:
      - key: NODE_VERSION
        value: 18.20.4
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
