services:
  - type: web
    name: pledgewise-api
    env: node
    buildCommand: npm install --prefix server && npm run build --prefix server
    startCommand: node server/dist/server.js
    envVars:
      - key: NODE_VERSION
        value: 18.20.4
      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
